object fraCollectSHA711: TfraCollectSHA711
  Left = 0
  Top = 0
  Width = 690
  Height = 645
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  ParentFont = False
  TabOrder = 0
  object Label1: TLabel
    Left = 8
    Top = 10
    Width = 243
    Height = 16
    Caption = #1043' '#1054' '#1056' '#1054' '#1044'   '#1057' '#1045' '#1058' '#1045' '#1042' '#1040' '#1071'   '#1042' '#1054' '#1044' '#1040
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Label2: TLabel
    Left = 8
    Top = 236
    Width = 351
    Height = 16
    Caption = #1055' '#1056' '#1054' '#1052' '#1067' '#1064' '#1051' '#1045' '#1053' '#1053' '#1067' '#1045'   '#1055' '#1054' '#1058' '#1056' '#1045' '#1041' '#1048' '#1058' '#1045' '#1051' '#1048
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object Edit25: TEdit
    Left = 8
    Top = 31
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 0
    Text = #1053#1072#1080#1084#1077#1085#1086#1074#1072#1085#1080#1077' '#1087#1072#1088#1072#1084#1077#1090#1088#1072
  end
  object Edit26: TEdit
    Left = 8
    Top = 52
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 1
    Text = '700-1'
  end
  object Edit27: TEdit
    Left = 8
    Top = 73
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 2
    Text = '600'
  end
  object Edit28: TEdit
    Left = 8
    Top = 94
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 3
    Text = '700'
  end
  object Edit29: TEdit
    Left = 8
    Top = 115
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 4
    Text = '800'
  end
  object Edit30: TEdit
    Left = 8
    Top = 178
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 5
    Text = #1050#1086#1083#1083#1077#1082#1090#1086#1088' N1'
  end
  object Edit31: TEdit
    Left = 8
    Top = 199
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 6
    Text = #1050#1086#1083#1083#1077#1082#1090#1086#1088' N2'
  end
  object Edit100: TEdit
    Left = 8
    Top = 157
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 7
    Text = '1000'
  end
  object OPCEdit26: TOPCEdit
    Left = 395
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 8
    Text = 'P_pr_vod_700_1gor'
    OPCTag = 'P_pr_vod_700_1gor'
  end
  object OPCEdit30: TOPCEdit
    Left = 395
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 9
    Text = 'P_pr_vod_700gor'
    OPCTag = 'P_pr_vod_700gor'
  end
  object OPCEdit39: TOPCEdit
    Left = 395
    Top = 199
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 10
    Text = 'P_kolprsetv2'
    OPCTag = 'P_kolprsetv2'
  end
  object OPCEdit95: TOPCEdit
    Left = 464
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 11
    Text = 'P_obr_vod_700_1gor'
    OPCTag = 'P_obr_vod_700_1gor'
  end
  object OPCEdit97: TOPCEdit
    Left = 464
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 12
    Text = 'P_obr_vod_700gor'
    OPCTag = 'P_obr_vod_700gor'
  end
  object OPCEdit99: TOPCEdit
    Left = 464
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 13
    Text = 'P_obr_vod_1000gorNGVS'
    OPCTag = 'P_obr_vod_1000gorNGVS'
  end
  object OPCEdit100: TOPCEdit
    Left = 464
    Top = 199
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 14
    Text = 'P_kolobsetv2'
    OPCTag = 'P_kolobsetv2'
  end
  object OPCEdit104: TOPCEdit
    Left = 533
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 15
    Text = 'T_pr_vod_700_1gor'
    OPCTag = 'T_pr_vod_700_1gor'
  end
  object OPCEdit106: TOPCEdit
    Left = 533
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 16
    Text = 'T_pr_vod_600gor'
    OPCTag = 'T_pr_vod_600gor'
  end
  object OPCEdit108: TOPCEdit
    Left = 533
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 17
    Text = 'T_pr_vod_700gor'
    OPCTag = 'T_pr_vod_700gor'
  end
  object OPCEdit112: TOPCEdit
    Left = 533
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 18
    Text = 'T_pr_vod_800gorNGVS'
    OPCTag = 'T_pr_vod_800gorNGVS'
  end
  object OPCEdit113: TOPCEdit
    Left = 533
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 19
    Text = 'T_pr_vod_1000gorNGVS'
    OPCTag = 'T_pr_vod_1000gorNGVS'
  end
  object OPCEdit125: TOPCEdit
    Left = 602
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 20
    Text = 'T_obr_vod_700_1gor'
    OPCTag = 'T_obr_vod_700_1gor'
  end
  object OPCEdit126: TOPCEdit
    Left = 602
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 21
    Text = 'T_obr_vod_600gor'
    OPCTag = 'T_obr_vod_600gor'
  end
  object OPCEdit128: TOPCEdit
    Left = 602
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 22
    Text = 'T_obr_vod_700gor'
    OPCTag = 'T_obr_vod_700gor'
  end
  object OPCEdit130: TOPCEdit
    Left = 602
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 23
    Text = 'T_obr_vod_800gorNGVS'
    OPCTag = 'T_obr_vod_800gorNGVS'
  end
  object OPCEdit132: TOPCEdit
    Left = 602
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 24
    Text = 'T_obr_vod_1000gorNGVS'
    OPCTag = 'T_obr_vod_1000gorNGVS'
  end
  object Edit101: TEdit
    Left = 257
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 25
    Text = 'Q '#1087#1088' ('#1090'/'#1095')'
  end
  object Edit102: TEdit
    Left = 326
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 26
    Text = 'Q '#1086#1073' ('#1090'/'#1095')'
  end
  object Edit103: TEdit
    Left = 395
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 27
    Text = #1056' '#1087#1088' ('#1082#1075'/'#1089#1084'2)'
  end
  object Edit104: TEdit
    Left = 464
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 28
    Text = #1056' '#1086#1073' ('#1082#1075'/'#1089#1084'2)'
  end
  object Edit105: TEdit
    Left = 533
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 29
    Text = #1058' '#1087#1088' ('#1057')'
  end
  object Edit106: TEdit
    Left = 602
    Top = 31
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 30
    Text = #1058' '#1086#1073' ('#1057')'
  end
  object OPCEdit189: TOPCEdit
    Left = 395
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 31
    Text = 'P_pr_vod_600gor'
    OPCTag = 'P_pr_vod_600gor'
  end
  object OPCEdit190: TOPCEdit
    Left = 464
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 32
    Text = 'P_obr_vod_600gor'
    OPCTag = 'P_obr_vod_600gor'
  end
  object OPCEdit193: TOPCEdit
    Left = 395
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 33
    Text = 'P_pr_vod_800gorNGVS'
    OPCTag = 'P_pr_vod_800gorNGVS'
  end
  object OPCEdit194: TOPCEdit
    Left = 464
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 34
    Text = 'P_obr_vod_800gorNGVS'
    OPCTag = 'P_obr_vod_800gorNGVS'
  end
  object OPCEdit197: TOPCEdit
    Left = 395
    Top = 178
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 35
    Text = 'P_kolprsetv1'
    OPCTag = 'P_kolprsetv1'
  end
  object OPCEdit198: TOPCEdit
    Left = 464
    Top = 178
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 36
    Text = 'P_kolobsetv1'
    OPCTag = 'P_kolobsetv1'
  end
  object P_pr_vod_1000gorNGVS: TOPCEdit
    Left = 395
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 37
    Text = 'P_pr_vod_1000gorNGVS'
    OPCTag = 'P_pr_vod_1000gorNGVS'
  end
  object Edit2: TEdit
    Left = 8
    Top = 258
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 38
    Text = '600 '#1059#1052#1047
  end
  object Edit3: TEdit
    Left = 8
    Top = 279
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 39
    Text = '700 '#1050#1072#1079#1094#1080#1085#1082
  end
  object Edit4: TEdit
    Left = 8
    Top = 300
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 40
    Text = #1058'. '#1074'. '#1052#1047
  end
  object Edit5: TEdit
    Left = 8
    Top = 351
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 41
    Text = #1059#1052#1047' 2'
  end
  object Edit6: TEdit
    Left = 8
    Top = 372
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 42
    Text = #1055#1088#1072#1095#1077#1095#1085#1072#1103
  end
  object Edit7: TEdit
    Left = 8
    Top = 330
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 43
    Text = #1059#1052#1047' 1'
  end
  object OPCEdit7: TOPCEdit
    Left = 257
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 44
    Text = 'Qpr700SSK'
    OPCTag = 'Qpr700SSK'
  end
  object OPCEdit8: TOPCEdit
    Left = 257
    Top = 330
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 45
    Text = 'QparUMZ1n'
    OPCTag = 'QparUMZ1n'
  end
  object OPCEdit9: TOPCEdit
    Left = 257
    Top = 372
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 46
    Text = 'G_par_Prachechn'
    OPCTag = 'G_par_Prachechn'
  end
  object OPCEdit13: TOPCEdit
    Left = 326
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 47
    Text = 'Qob700SSK'
    OPCTag = 'Qob700SSK'
  end
  object OPCEdit18: TOPCEdit
    Left = 395
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 48
    Text = 'Qpr700SSK'
    OPCTag = 'Qpr700SSK'
  end
  object OPCEdit19: TOPCEdit
    Left = 395
    Top = 372
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 49
    Text = 'P_par_Prachechn'
    OPCTag = 'P_par_Prachechn'
  end
  object OPCEdit21: TOPCEdit
    Left = 464
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 50
    Text = 'Qob700SSK'
    OPCTag = 'Qob700SSK'
  end
  object OPCEdit25: TOPCEdit
    Left = 533
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 51
    Text = 'Tpr600UMZ'
    OPCTag = 'Tpr600UMZ'
  end
  object OPCEdit27: TOPCEdit
    Left = 533
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 52
    Text = 'Tpr700SSK'
    OPCTag = 'Tpr700SSK'
  end
  object OPCEdit29: TOPCEdit
    Left = 533
    Top = 330
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 53
    Text = 'TparUMZ1n'
    OPCTag = 'TparUMZ1n'
  end
  object OPCEdit31: TOPCEdit
    Left = 533
    Top = 351
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 54
    Text = 'TparUMZ2n'
    OPCTag = 'TparUMZ2n'
  end
  object OPCEdit32: TOPCEdit
    Left = 533
    Top = 372
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 55
    Text = 'T_par_Prachechn'
    OPCTag = 'T_par_Prachechn'
  end
  object OPCEdit34: TOPCEdit
    Left = 602
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 56
    Text = 'Tob600UMZ'
    OPCTag = 'Tob600UMZ'
  end
  object OPCEdit35: TOPCEdit
    Left = 602
    Top = 279
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 57
    Text = 'Tob700SSK'
    OPCTag = 'Tob700SSK'
  end
  object OPCEdit41: TOPCEdit
    Left = 257
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 58
    Text = 'Qpr600UMZ'
    OPCTag = 'Qpr600UMZ'
  end
  object OPCEdit42: TOPCEdit
    Left = 326
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 59
    Text = 'Qob600UMZ'
    OPCTag = 'Qob600UMZ'
  end
  object OPCEdit43: TOPCEdit
    Left = 395
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 60
    Text = 'Ppr600UMZ'
    OPCTag = 'Ppr600UMZ'
  end
  object OPCEdit44: TOPCEdit
    Left = 464
    Top = 258
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 61
    Text = 'Pob600UMZ'
    OPCTag = 'Pob600UMZ'
  end
  object OPCEdit45: TOPCEdit
    Left = 257
    Top = 300
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 62
    Text = 'QtexvM_Z'
    OPCTag = 'QtexvM_Z'
  end
  object OPCEdit47: TOPCEdit
    Left = 395
    Top = 300
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 63
    Text = 'PtexvM_Z'
    OPCTag = 'PtexvM_Z'
  end
  object OPCEdit49: TOPCEdit
    Left = 257
    Top = 351
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 64
    Text = 'QparUMZ2n'
    OPCTag = 'QparUMZ2n'
  end
  object OPCEdit51: TOPCEdit
    Left = 395
    Top = 351
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 65
    Text = 'PparUMZ2n'
    OPCTag = 'PparUMZ2n'
  end
  object OPCEdit53: TOPCEdit
    Left = 395
    Top = 330
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 66
    Text = 'PparUMZ1n'
    OPCTag = 'PparUMZ1n'
  end
  object Edit8: TEdit
    Left = 8
    Top = 393
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 67
    Text = #1042#1050' '#1055#1069#1056
  end
  object OPCEdit54: TOPCEdit
    Left = 257
    Top = 393
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 68
    Text = 'F_par_VK_PromEnergRem'
    OPCTag = 'F_par_VK_PromEnergRem'
  end
  object OPCEdit56: TOPCEdit
    Left = 395
    Top = 393
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 69
    Text = 'P_par_VK_PromEnergRem'
    OPCTag = 'P_par_VK_PromEnergRem'
  end
  object OPCEdit58: TOPCEdit
    Left = 533
    Top = 393
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 70
    Text = 'T_par_VK_PromEnergRem'
    OPCTag = 'T_par_VK_PromEnergRem'
  end
  object Edit9: TEdit
    Left = 257
    Top = 178
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 71
  end
  object Edit10: TEdit
    Left = 326
    Top = 178
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 72
  end
  object Edit11: TEdit
    Left = 257
    Top = 199
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 73
  end
  object Edit12: TEdit
    Left = 326
    Top = 199
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 74
  end
  object Edit13: TEdit
    Left = 533
    Top = 178
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 75
  end
  object Edit14: TEdit
    Left = 602
    Top = 178
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 76
  end
  object Edit15: TEdit
    Left = 602
    Top = 199
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 77
  end
  object Edit16: TEdit
    Left = 533
    Top = 199
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 78
  end
  object Edit17: TEdit
    Left = 326
    Top = 300
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 79
  end
  object Edit18: TEdit
    Left = 533
    Top = 300
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 80
  end
  object Edit19: TEdit
    Left = 602
    Top = 300
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 81
  end
  object Edit20: TEdit
    Left = 464
    Top = 300
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentCtl3D = False
    ParentFont = False
    ReadOnly = True
    TabOrder = 82
  end
  object Edit1: TEdit
    Left = 326
    Top = 330
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 83
  end
  object Edit21: TEdit
    Left = 326
    Top = 351
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 84
  end
  object Edit22: TEdit
    Left = 326
    Top = 372
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 85
  end
  object Edit23: TEdit
    Left = 326
    Top = 393
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 86
  end
  object Edit24: TEdit
    Left = 464
    Top = 330
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 87
  end
  object Edit32: TEdit
    Left = 464
    Top = 351
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 88
  end
  object Edit33: TEdit
    Left = 464
    Top = 372
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 89
  end
  object Edit34: TEdit
    Left = 464
    Top = 393
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 90
  end
  object Edit35: TEdit
    Left = 602
    Top = 330
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 91
  end
  object Edit36: TEdit
    Left = 602
    Top = 351
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 92
  end
  object Edit37: TEdit
    Left = 602
    Top = 372
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 93
  end
  object Edit38: TEdit
    Left = 602
    Top = 393
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 94
  end
  object Edit39: TEdit
    Left = 8
    Top = 489
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 95
    Text = #1058' '#1085#1072#1088#1091#1078#1085#1086#1075#1086' '#1074#1086#1079#1076#1091#1093#1072
  end
  object Edit40: TEdit
    Left = 8
    Top = 510
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 96
    Text = 'Q '#1094#1080#1088#1082'. '#1074#1086#1076#1099' '#1074#1086#1076#1086#1074#1086#1076' 3'
  end
  object Edit41: TEdit
    Left = 8
    Top = 531
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 97
    Text = 'Q '#1094#1080#1088#1082'. '#1074#1086#1076#1099' '#1074#1086#1076#1086#1074#1086#1076' 4'
  end
  object OPCEdit4: TOPCEdit
    Left = 257
    Top = 489
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 98
    Text = 'T_naruznvozdux'
    OPCTag = 'T_naruznvozdux'
  end
  object OPCEdit5: TOPCEdit
    Left = 257
    Top = 510
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 99
    Text = 'Qsirkvod3'
    OPCTag = 'Qsirkvod3'
  end
  object OPCEdit11: TOPCEdit
    Left = 257
    Top = 531
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 100
    Text = 'Qsirkvod4'
    OPCTag = 'Qsirkvod4'
  end
  object OPCEdit12: TOPCEdit
    Left = 326
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 101
    Text = 'G_obr_vod_1000gorNGVS'
    OPCTag = 'G_obr_vod_1000gorNGVS'
  end
  object OPCEdit192: TOPCEdit
    Left = 326
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 102
    Text = 'G_obr_vod_800gorNGVS'
    OPCTag = 'G_obr_vod_800gorNGVS'
  end
  object OPCEdit10: TOPCEdit
    Left = 326
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 103
    Text = 'G_obr_vod_700gor'
    OPCTag = 'G_obr_vod_700gor'
  end
  object OPCEdit188: TOPCEdit
    Left = 326
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 104
    Text = 'G_obr_vod_600gor'
    OPCTag = 'G_obr_vod_600gor'
  end
  object OPCEdit6: TOPCEdit
    Left = 326
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 105
    Text = 'G_obr_vod_700_1gor'
    OPCTag = 'G_obr_vod_700_1gor'
  end
  object OPCEdit1: TOPCEdit
    Left = 257
    Top = 52
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 106
    Text = 'G_pr_vod_700_1gor'
    OPCTag = 'G_pr_vod_700_1gor'
  end
  object OPCEdit187: TOPCEdit
    Left = 257
    Top = 73
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 107
    Text = 'G_pr_vod_600gor'
    OPCTag = 'G_pr_vod_600gor'
  end
  object OPCEdit2: TOPCEdit
    Left = 257
    Top = 94
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 108
    Text = 'G_pr_vod_700gor'
    OPCTag = 'G_pr_vod_700gor'
  end
  object OPCEdit191: TOPCEdit
    Left = 257
    Top = 115
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 109
    Text = 'G_pr_vod_800gorNGVS'
    OPCTag = 'G_pr_vod_800gorNGVS'
  end
  object OPCEdit3: TOPCEdit
    Left = 257
    Top = 157
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 110
    Text = 'G_pr_vod_1000gorNGVS'
    OPCTag = 'G_pr_vod_1000gorNGVS'
  end
  object Edit42: TEdit
    Left = 8
    Top = 136
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 111
    Text = '800 ['#1087#1077#1088#1077#1084#1099#1095#1082#1072']'
  end
  object OPCEdit14: TOPCEdit
    Left = 257
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 112
    Text = 'Qpr800gor'
    OPCTag = 'Qpr800gor'
  end
  object OPCEdit15: TOPCEdit
    Left = 326
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 113
    Text = 'Qob800gor'
    OPCTag = 'Qob800gor'
  end
  object OPCEdit16: TOPCEdit
    Left = 395
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 114
    Text = 'Ppr800gor'
    OPCTag = 'Ppr800gor'
  end
  object OPCEdit17: TOPCEdit
    Left = 464
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 115
    Text = 'Pob800gor'
    OPCTag = 'Pob800gor'
  end
  object OPCEdit20: TOPCEdit
    Left = 533
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 116
    Text = 'Tpr800gor'
    OPCTag = 'Tpr800gor'
  end
  object OPCEdit22: TOPCEdit
    Left = 602
    Top = 136
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 117
    Text = 'Tob800gor'
    OPCTag = 'Tob800gor'
  end
  object Edit43: TEdit
    Left = 8
    Top = 435
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 118
    Text = #1057#1062#1050' 400'
  end
  object Edit44: TEdit
    Left = 8
    Top = 456
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 119
    Text = #1057#1062#1050' 400-1'
  end
  object Edit45: TEdit
    Left = 8
    Top = 414
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 120
    Text = #1057#1062#1050' 200'
  end
  object OPCEdit23: TOPCEdit
    Left = 257
    Top = 414
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 121
    Text = 'Q_nn_200_SCK'
    OPCTag = 'Q_nn_200_SCK'
  end
  object OPCEdit24: TOPCEdit
    Left = 257
    Top = 456
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 122
    Text = 'Q_para_400-1'
    OPCTag = 'Q_para_400-1'
  end
  object OPCEdit28: TOPCEdit
    Left = 395
    Top = 456
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 123
    Text = 'P_para_400-1'
    OPCTag = 'P_para_400-1'
  end
  object OPCEdit36: TOPCEdit
    Left = 533
    Top = 435
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 124
    Text = 'T_par_SCK'
    OPCTag = 'T_par_SCK'
  end
  object OPCEdit38: TOPCEdit
    Left = 257
    Top = 435
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 125
    Text = 'Q_nn_400_SCK'
    OPCTag = 'Q_nn_400_SCK'
  end
  object OPCEdit40: TOPCEdit
    Left = 395
    Top = 435
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 126
    Text = 'P_nn_400_SCK'
    OPCTag = 'P_nn_400_SCK'
  end
  object OPCEdit46: TOPCEdit
    Left = 395
    Top = 414
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 127
    Text = 'P_par_200'
    OPCTag = 'P_par_200'
  end
  object Edit46: TEdit
    Left = 326
    Top = 414
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 128
  end
  object Edit47: TEdit
    Left = 326
    Top = 435
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 129
  end
  object Edit48: TEdit
    Left = 326
    Top = 456
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 130
  end
  object Edit49: TEdit
    Left = 464
    Top = 414
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 131
  end
  object Edit50: TEdit
    Left = 464
    Top = 435
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 132
  end
  object Edit51: TEdit
    Left = 464
    Top = 456
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 133
  end
  object Edit52: TEdit
    Left = 602
    Top = 414
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 134
  end
  object Edit53: TEdit
    Left = 602
    Top = 435
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 135
  end
  object Edit54: TEdit
    Left = 602
    Top = 456
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 136
  end
  object Edit55: TEdit
    Left = 533
    Top = 456
    Width = 70
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 137
  end
  object Edit56: TEdit
    Left = 8
    Top = 590
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 138
    Text = '(F) '#1056#1072#1089#1093#1086#1076' ('#1084'3/'#1095')'
  end
  object Edit57: TEdit
    Left = 8
    Top = 611
    Width = 250
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 139
    Text = '(V) '#1054#1073#1098#1077#1084' '#1085#1072#1088#1072#1089#1090#1072#1102#1097#1080#1084' '#1080#1090#1086#1075#1086#1084' ('#1084'3)'
  end
  object OPCEdit48: TOPCEdit
    Left = 311
    Top = 590
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 140
    Text = 'F_vod_Rash_TC'
    OPCTag = 'F_vod_Rash_TC'
  end
  object OPCEdit50: TOPCEdit
    Left = 311
    Top = 611
    Width = 70
    Height = 22
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 141
    Text = 'V_NarItog_Rash_TC'
    OPCTag = 'V_NarItog_Rash_TC'
  end
  object Edit59: TEdit
    Left = 277
    Top = 569
    Width = 140
    Height = 22
    BevelInner = bvNone
    BevelOuter = bvNone
    Color = clBtnFace
    Ctl3D = False
    ParentCtl3D = False
    ReadOnly = True
    TabOrder = 142
    Text = #1042#1086#1076#1072' '#1085#1072' '#1088#1072#1089#1093#1086#1083'. '#1058#1057
  end
end
