unit FrameSummary;

interface

uses 
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  StdCtrls, OPCEdit, ExtCtrls;

type
  TfraSummary = class(TFrame)
    OPCEdit7: TOPCEdit;
    OPCEdit9: TOPCEdit;
    OPCEdit11: TOPCEdit;
    OPCEdit13: TOPCEdit;
    OPCEdit15: TOPCEdit;
    OPCEdit16: TOPCEdit;
    OPCEdit18: TOPCEdit;
    OPCEdit20: TOPCEdit;
    OPCEdit22: TOPCEdit;
    OPCEdit24: TOPCEdit;
    OPCEdit25: TOPCEdit;
    OPCEdit27: TOPCEdit;
    OPCEdit31: TOPCEdit;
    OPCEdit33: TOPCEdit;
    OPCEdit34: TOPCEdit;
    OPCEdit36: TOPCEdit;
    OPCEdit38: TOPCEdit;
    OPCEdit40: TOPCEdit;
    OPCEdit42: TOPCEdit;
    OPCEdit43: TOPCEdit;
    OPCEdit44: TOPCEdit;
    OPCEdit45: TOPCEdit;
    OPCEdit46: TOPCEdit;
    OPCEdit47: TOPCEdit;
    OPCEdit48: TOPCEdit;
    OPCEdit49: TOPCEdit;
    OPCEdit50: TOPCEdit;
    OPCEdit51: TOPCEdit;
    OPCEdit52: TOPCEdit;
    OPCEdit53: TOPCEdit;
    OPCEdit54: TOPCEdit;
    OPCEdit55: TOPCEdit;
    OPCEdit56: TOPCEdit;
    OPCEdit57: TOPCEdit;
    OPCEdit58: TOPCEdit;
    OPCEdit59: TOPCEdit;
    OPCEdit60: TOPCEdit;
    OPCEdit61: TOPCEdit;
    OPCEdit62: TOPCEdit;
    OPCEdit63: TOPCEdit;
    OPCEdit64: TOPCEdit;
    OPCEdit65: TOPCEdit;
    OPCEdit66: TOPCEdit;
    OPCEdit67: TOPCEdit;
    OPCEdit68: TOPCEdit;
    OPCEdit69: TOPCEdit;
    OPCEdit70: TOPCEdit;
    OPCEdit71: TOPCEdit;
    OPCEdit72: TOPCEdit;
    OPCEdit73: TOPCEdit;
    OPCEdit74: TOPCEdit;
    OPCEdit75: TOPCEdit;
    OPCEdit76: TOPCEdit;
    OPCEdit77: TOPCEdit;
    OPCEdit78: TOPCEdit;
    OPCEdit79: TOPCEdit;
    OPCEdit81: TOPCEdit;
    OPCEdit83: TOPCEdit;
    OPCEdit85: TOPCEdit;
    OPCEdit86: TOPCEdit;
    OPCEdit87: TOPCEdit;
    OPCEdit8: TOPCEdit;
    OPCEdit14: TOPCEdit;
    OPCEdit19: TOPCEdit;
    OPCEdit23: TOPCEdit;
    OPCEdit28: TOPCEdit;
    OPCEdit32: TOPCEdit;
    OPCEdit111: TOPCEdit;
    OPCEdit114: TOPCEdit;
    OPCEdit116: TOPCEdit;
    OPCEdit118: TOPCEdit;
    OPCEdit120: TOPCEdit;
    OPCEdit122: TOPCEdit;
    OPCEdit123: TOPCEdit;
    OPCEdit124: TOPCEdit;
    OPCEdit127: TOPCEdit;
    OPCEdit129: TOPCEdit;
    OPCEdit131: TOPCEdit;
    OPCEdit133: TOPCEdit;
    OPCEdit135: TOPCEdit;
    OPCEdit136: TOPCEdit;
    OPCEdit137: TOPCEdit;
    OPCEdit140: TOPCEdit;
    OPCEdit141: TOPCEdit;
    OPCEdit142: TOPCEdit;
    OPCEdit143: TOPCEdit;
    OPCEdit144: TOPCEdit;
    OPCEdit145: TOPCEdit;
    OPCEdit146: TOPCEdit;
    OPCEdit147: TOPCEdit;
    OPCEdit148: TOPCEdit;
    OPCEdit149: TOPCEdit;
    OPCEdit150: TOPCEdit;
    OPCEdit151: TOPCEdit;
    OPCEdit152: TOPCEdit;
    OPCEdit153: TOPCEdit;
    OPCEdit154: TOPCEdit;
    OPCEdit155: TOPCEdit;
    OPCEdit156: TOPCEdit;
    OPCEdit157: TOPCEdit;
    OPCEdit158: TOPCEdit;
    OPCEdit163: TOPCEdit;
    OPCEdit164: TOPCEdit;
    OPCEdit165: TOPCEdit;
    OPCEdit166: TOPCEdit;
    OPCEdit167: TOPCEdit;
    OPCEdit168: TOPCEdit;
    OPCEdit169: TOPCEdit;
    OPCEdit170: TOPCEdit;
    OPCEdit171: TOPCEdit;
    OPCEdit98: TOPCEdit;
    OPCEdit101: TOPCEdit;
    OPCEdit103: TOPCEdit;
    OPCEdit105: TOPCEdit;
    OPCEdit107: TOPCEdit;
    OPCEdit109: TOPCEdit;
    OPCEdit110: TOPCEdit;
    Edit1: TEdit;
    Edit2: TEdit;
    Edit3: TEdit;
    Edit4: TEdit;
    Edit5: TEdit;
    Edit6: TEdit;
    Edit7: TEdit;
    Edit8: TEdit;
    Edit9: TEdit;
    Edit10: TEdit;
    Edit11: TEdit;
    Edit12: TEdit;
    Edit13: TEdit;
    Edit14: TEdit;
    Edit15: TEdit;
    Edit16: TEdit;
    Edit17: TEdit;
    Edit18: TEdit;
    Edit19: TEdit;
    Edit20: TEdit;
    Edit21: TEdit;
    Edit22: TEdit;
    Edit23: TEdit;
    Edit24: TEdit;
    Edit33: TEdit;
    Edit34: TEdit;
    Edit35: TEdit;
    Edit36: TEdit;
    Edit37: TEdit;
    Edit38: TEdit;
    Edit39: TEdit;
    Edit40: TEdit;
    Edit42: TEdit;
    Edit43: TEdit;
    Edit44: TEdit;
    Edit45: TEdit;
    Edit46: TEdit;
    Edit47: TEdit;
    Edit48: TEdit;
    Edit49: TEdit;
    Edit50: TEdit;
    Edit51: TEdit;
    Edit52: TEdit;
    Edit53: TEdit;
    Edit54: TEdit;
    Edit55: TEdit;
    Edit56: TEdit;
    Edit57: TEdit;
    Edit58: TEdit;
    Edit59: TEdit;
    Edit60: TEdit;
    Edit61: TEdit;
    Edit62: TEdit;
    Edit63: TEdit;
    Edit64: TEdit;
    Edit65: TEdit;
    Edit66: TEdit;
    Edit67: TEdit;
    Edit68: TEdit;
    Edit69: TEdit;
    Edit70: TEdit;
    Edit71: TEdit;
    Edit72: TEdit;
    Edit73: TEdit;
    Edit74: TEdit;
    Edit75: TEdit;
    Edit76: TEdit;
    Edit77: TEdit;
    Edit78: TEdit;
    Edit79: TEdit;
    Edit80: TEdit;
    Edit81: TEdit;
    Edit82: TEdit;
    Edit83: TEdit;
    Edit84: TEdit;
    Edit85: TEdit;
    Edit86: TEdit;
    Edit87: TEdit;
    Edit88: TEdit;
    Edit89: TEdit;
    Edit90: TEdit;
    Edit91: TEdit;
    Edit92: TEdit;
    Edit93: TEdit;
    Edit94: TEdit;
    Edit95: TEdit;
    Edit96: TEdit;
    Edit97: TEdit;
    Edit98: TEdit;
    Edit99: TEdit;
    OPCEdit29: TOPCEdit;
    Edit25: TEdit;
    Edit26: TEdit;
    Edit27: TEdit;
    Edit28: TEdit;
    OPCEdit4: TOPCEdit;
    Edit29: TEdit;
    OPCEdit1: TOPCEdit;
    Edit30: TEdit;
    OPCEdit2: TOPCEdit;
    Edit31: TEdit;
    OPCEdit3: TOPCEdit;
    Edit32: TEdit;
    Edit41: TEdit;
    Edit100: TEdit;
    Edit101: TEdit;
    Edit102: TEdit;
    Edit103: TEdit;
    StaticText17: TStaticText;
    StaticText1: TStaticText;
    StaticText2: TStaticText;
    StaticText3: TStaticText;
    TimerSummaryPP: TTimer;
    Edit104: TEdit;
    Edit105: TEdit;
    Edit106: TEdit;
    Edit107: TEdit;
    Edit108: TEdit;
    Edit109: TEdit;
    Edit110: TEdit;
    Edit111: TEdit;
    Edit112: TEdit;
    Edit113: TEdit;
    Edit114: TEdit;
    Edit115: TEdit;
    OPCEdit5: TOPCEdit;
    Edit116: TEdit;
    OPCEdit6: TOPCEdit;
    OPCEdit10: TOPCEdit;
    OPCEdit12: TOPCEdit;
    OPCEdit21: TOPCEdit;
    OPCEdit30: TOPCEdit;
    OPCEdit37: TOPCEdit;
    Edit117: TEdit;
    Edit118: TEdit;
    Edit119: TEdit;
    Edit121: TEdit;
    Edit122: TEdit;
    Edit123: TEdit;
    Edit124: TEdit;
    Edit125: TEdit;
    OPCEdit17: TOPCEdit;
    Edit120: TEdit;
    OPCEdit26: TOPCEdit;
    Edit126: TEdit;
    OPCEdit35: TOPCEdit;
    procedure FrameEnter(Sender: TObject);
    procedure TimerSummaryPPTimer(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

implementation

{$R *.dfm}

Uses
  MyCl;

procedure TfraSummary.FrameEnter(Sender: TObject);
begin
  TimerSummaryPP.Enabled:=False;
  TimerSummaryPP.Interval:=frmOPClient.seTimer.Value*100;
  TimerSummaryPP.Enabled:=True;
end;

procedure TfraSummary.TimerSummaryPPTimer(Sender: TObject);
begin
  StaticText17.Caption:=FormatFloat('0.00',StrToFloat(OPCEdit43.Text)+StrToFloat(OPCEdit44.Text));
  StaticText1.Caption:=FormatFloat('0.00',StrToFloat(OPCEdit52.Text)+StrToFloat(OPCEdit53.Text));
  StaticText2.Caption:=FormatFloat('0.00',StrToFloat(OPCEdit61.Text)+StrToFloat(OPCEdit62.Text));
  StaticText3.Caption:=FormatFloat('0.00',StrToFloat(OPCEdit70.Text)+StrToFloat(OPCEdit71.Text));
end;

end.
